config/routes.rb
Rails.application.routes.draw do
  resources :discounts
  resources :tax_categories
  resources :orders, except: [:edit, :update]
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "items#index"
end

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this <%= object.class %> from being saved:</h2>

    <ul>
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Coffee Shop', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarItemDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Items
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarItemDropdown">
            <li><%= link_to 'Items', items_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'Add new Item', new_item_path, class: 'dropdown-item' %></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarOrderDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Orders
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarOrderDropdown">
            <li><%= link_to 'Orders', orders_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'Create Order', new_order_path, class: 'dropdown-item' %></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarTaxCategoryDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Tax Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarTaxCategoryDropdown">
            <li><%= link_to 'Tax Categories', tax_categories_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'Create Tax Category', new_tax_category_path, class: 'dropdown-item' %></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDiscountDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Discounts
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDiscountDropdown">
            <li><%= link_to 'Discounts', discounts_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'Create Discount', new_discount_path, class: 'dropdown-item' %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>