config/routes.rb
Rails.application.routes.draw do
  resources :discounts
  resources :tax_categories
  resources :orders, except: [:edit, :update]
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "items#index"
end

app/models/order.rb
class Order < ApplicationRecord
  # associations
  has_many :order_items, dependent: :destroy
  accepts_nested_attributes_for :order_items, allow_destroy: true, reject_if: :all_blank

  # validations
  validates :customer_name, presence: true
  validates :customer_email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :customer_mobile, length: { is: 10 }
  validate :has_order_items

  # callbacks
  before_save :calculate_order_item_price_and_tax
  # to calculate and save grand total of all order_items
  after_save :save_grand_total

  def customer_details
    "#{customer_name},\n#{customer_email},\n#{customer_mobile}"
  end

  private

  def save_grand_total
    total = order_items.sum(:total_price)
    return if grand_total == total

    update(grand_total: total)
  end

  def calculate_order_item_price_and_tax
    discounted_items = {}
    self.order_items.each do |order_item|
      discount = Discount.find_by(base_item_id: order_item.item_id)
      if discount.present? && order_item.quantity >= discount.base_item_quantity
        qty_multiplier = (discount.base_item_id == discount.child_item_id) ? 2 : 1
        discount_multiplier = order_item.quantity / (discount.base_item_quantity * qty_multiplier)

        d_total_qty_cal = discount.child_item_quantity * discount_multiplier
        d_total_qty_cal = d_total_qty_cal >= order_item.quantity ? order_item.quantity : d_total_qty_cal

        d_total_qty = (d_total_qty_cal * discount.discount_percent.to_f) / 100
        discounted_items[discount.child_item_id] = discounted_items[discount.child_item_id] ? discounted_items[discount.child_item_id] + d_total_qty : d_total_qty
      end

      # order_item (base) price, tax calculation
      total = order_item.item.price * order_item.quantity
      tax = (order_item.item.tax_category.tax_rate.to_f * total ) / 100
      order_item.tax_value = tax
      order_item.total_price = total + tax
    end

    if discounted_items.present?
      discounted_items.each do |child_item_id, discounted_qty|
        order_item = self.order_items.select{ |order_item| order_item.item_id == child_item_id }.first
        if order_item
          total_qty = order_item.quantity
          item = Item.find(child_item_id)
          total_oi_price = item.price * total_qty
          discounted_oi_price = item.price * discounted_qty
          total_price = total_oi_price - discounted_oi_price
          tax = (item.tax_category.tax_rate.to_f * total_price) / 100
          order_item.tax_value = tax
          order_item.total_price = total_price + tax
        end
        discounted_items.delete(child_item_id)
      end
    end
  end

  def has_order_items
    errors.add(:base, "No items added") unless self.order_items.present?
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @order.order_items.build
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        OrdersMailer.with(name: @order.customer_name, email: @order.customer_email, order_id: @order.id).order_prepaired.deliver_now
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:customer_name, :customer_email, :customer_mobile, order_items_attributes: [:id, :quantity, :item_id, :destroy])
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def link_to_add_order_item(name, order_form, association)
    new_object = order_form.object.send(association).klass.new
    id = new_object.object_id
    fields = order_form.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", order_form: builder)
    end
    link_to(name, '#', class: "add_order_item btn btn-info", data: { id: id, fields: fields.gsub("\n", ""), controller: 'user-modal' })
  end
end

app/views/orders/_form.html.erb
<%= form_with(model: order, html: { class: "row g-3" }) do |order_form| %>
  <%= render 'shared/errors', object: order %>

  <div class="col-md-3">
    <%= order_form.label :customer_name, class: "form-label" %>
    <%= order_form.text_field :customer_name, class: "form-control" %>
  </div>

  <div class="col-md-3">
    <%= order_form.label :customer_email, class: "form-label" %>
    <%= order_form.text_field :customer_email, class: "form-control" %>
  </div>

  <div class="col-md-3">
    <%= order_form.label :customer_mobile, class: "form-label" %>
    <%= order_form.text_field :customer_mobile, class: "form-control" %>
  </div>

  <div id="order_items" data-controller='orders' style="display: flex">
    <%= order_form.fields_for :order_items do |builder| %>
      <%= render 'order_item_fields', order_form: builder %>
    <% end %>
  </div>

  <div class="col-12">
    <%= link_to_add_order_item('Add Item', order_form, :order_items) %>
  </div>

  <div class="col-12">
    <%= order_form.submit "Submit", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>Grand total:</strong>
    <%= order.grand_total %>
  </p>
</div>

app/views/orders/_order_item_fields.html.erb
<div class='nested-fields ms-3'>
  <div class="card">
    <div class="card-body">
      <div class="col-md-8">
        <%= order_form.label :item, class: "form-label"%>
        <%= order_form.collection_select(:item_id, Item.available, 'id', 'name', { prompt: 'Select Item' }, { class: "form-select" }) %>
      </div>

      <div class="col-md-8 mb-3">
        <%= order_form.label :quantity, class: "form-label" %>
        <%= order_form.number_field :quantity, class: "form-control" %>
      </div>

      <div class="col-12">
        <%= link_to 'Remove Item', '#', class: 'remove_order_item btn btn-danger' %>
      </div>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<h1>Orders</h1>

<% @orders.each do |order| %>
  <table class="table">
    <thead>
      <tr class='border'>
        <th><%= link_to "Order No.#{order.id}", order %></th>
      </tr>
      <tr class='border'>
        <th scope="col" class='border'>Name</th>
        <th scope="col" class='border'>Price/Item</th>
        <th scope="col" class='border'>Quantity</th>
        <th scope="col" class='border'>Total</th>
      </tr>
    </thead>
    <tbody>
      <% order.order_items.each do |order_item| %>
        <tr>
          <th scope="col" class='border'><%= order_item.item.name %></th>
          <td scope="col" class='border'><%= order_item.item.price %></td>
          <td scope="col" class='border'><%= order_item.quantity %></td>
          <td scope="col" class='border'><%= order_item.total_price %></td>
        </tr>
      <% end %>
      <tr class='border'>
        <th colspan='3' class='border'>Grand Total</th>
        <td colspan='2' class='border'><%= order.grand_total %></td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

app/views/orders/show.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col" colspan='5' class='border'><%= "Order##{@order.id}" %></th>
      <td scope="col" colspan='1' class='border'>
        <%= link_to "Destroy", order_path(@order), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        } %>
      </td>
    </tr>
    <tr>
      <th scope="col" colspan='1' class='border'>Customer Details</th>
      <td scope="col" colspan='5' class='border'><pre><%= @order.customer_details %></pre></td>
    </tr>
    <tr>
      <th scope="col" class='border'>Name</th>
      <th scope="col" class='border'>Price/Item</th>
      <th scope="col" class='border'>Quantity</th>
      <th scope="col" class='border'>Tax %</th>
      <th scope="col" class='border'>Tax Value</th>
      <th scope="col" class='border'>Total</th>
    </tr>
  </thead>
  <tbody>
    <% @order.order_items.each do |order_item| %>
      <tr>
        <th scope="col" class='border'><%= order_item.item.name %></th>
        <td scope="col" class='border'><%= order_item.item.price %></td>
        <td scope="col" class='border'><%= order_item.quantity %></td>
        <td scope="col" class='border'><%= order_item.item.tax_category.tax_rate %></td>
        <td scope="col" class='border'><%= order_item.tax_value %></td>
        <td scope="col" class='border'><%= order_item.total_price %></td>
      </tr>
    <% end %>
    <tr class='border'>
      <th colspan='5' class='border'>Grand Total</th>
      <th colspan='1' class='border'><%= @order.grand_total %></td>
    </tr>
  </tbody>
</table>