config/routes.rb
Rails.application.routes.draw do
  resources :discounts
  resources :tax_categories
  resources :orders, except: [:edit, :update]
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "items#index"
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  scope :available, -> { where(availability: true) }
  belongs_to :tax_category
  has_one :discount
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :price, :availability, :tax_category_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, html: { class: "row g-3" }) do |form| %>
  <%= render 'shared/errors', object: item %>

  <div class="col-md-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="col-md-1">
    <%= form.label :price, class: "form-label" %>
    <%= form.text_field :price, class: "form-control" %>
  </div>

  <div class="col-md-3">
    <%= form.label :tax_category_id, class: "form-label" %>
    <%= form.collection_select(:tax_category_id, TaxCategory.all, 'id', 'tax_rate',  { prompt: 'Select Tax Value' }, { class: "form-select" }) %>
  </div>

  <div class="col-12">
    <div class="form-check">
      <%= form.label :availability, class: "form-check-label" %>
      <%= form.check_box :availability, class: "form-check-input" %>
    </div>
  </div>

  <div class="col-12">
    <%= form.submit "Submit", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/items/_item.html.erb
<tr id="<%= dom_id item %>">
  <th scope="col" class='border'><%= item.name %></th>
  <td scope="col" class='border'><%= item.price %></td>
  <td scope="col" class='border'><%= item.availability %></td>
  <td scope="col" class='border'><%= item.tax_category.tax_rate %></td>
  <td scope="col" class='border'><%= link_to "Show this item", item, class: 'btn btn-secondary' %></td>
</tr>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item, class: 'btn btn-secondary' %>
  <%= link_to "Back to items", items_path, class: 'btn btn-secondary' %>
</div>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Items</h1>

<%= link_to "New Items", new_item_path, class: 'btn btn-info' %>

<table class="table caption-top">
  <thead>
    <tr>
      <th scope="col" class='border'>Name</th>
      <th scope="col" class='border'>Price</th>
      <th scope="col" class='border'>Availability</th>
      <th scope="col" class='border'>Tax Percent</th>
      <th scope="col" class='border'>Action</th>
    </tr>
  </thead>
  <tbody>
    <div id="items">
      <% @items.each do |item| %>
        <%= render item %>
      <%end%>
    </div>
  </tbody>
</table>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path, class: 'btn btn-secondary' %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<div id="<%= dom_id @item %>">
  <p>
    <strong>Name:</strong>
    <%= @item.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @item.price %>
  </p>

  <p>
    <strong>Tax Percent:</strong>
    <%= @item.tax_category.tax_rate %>
  </p>

  <p>
    <strong>Availability:</strong>
    <%= @item.availability %>
  </p>

</div>

<div>
  <%= link_to "Edit this item", edit_item_path(@item), class: "btn btn-secondary" %>
  <%= link_to "Back to items", items_path, class: "btn btn-secondary" %>
  <%= button_to "Destroy this item", @item, method: :delete, class: "btn btn-danger" %>
</div>