config/routes.rb
Rails.application.routes.draw do
  resources :discounts
  resources :tax_categories
  resources :orders, except: [:edit, :update]
  resources :items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "items#index"
end

app/models/tax_category.rb
class TaxCategory < ApplicationRecord
  has_many :items
  validates :tax_rate, uniqueness: true, numericality: { in: 0..100, message: "%{value} must be between 0 to 100" }
end

app/controllers/tax_categories_controller.rb
class TaxCategoriesController < ApplicationController
  before_action :set_tax_category, only: %i[ show edit update destroy ]

  # GET /tax_categories or /tax_categories.json
  def index
    @tax_categories = TaxCategory.all
  end

  # GET /tax_categories/1 or /tax_categories/1.json
  def show
  end

  # GET /tax_categories/new
  def new
    @tax_category = TaxCategory.new
  end

  # GET /tax_categories/1/edit
  def edit
  end

  # POST /tax_categories or /tax_categories.json
  def create
    @tax_category = TaxCategory.new(tax_category_params)

    respond_to do |format|
      if @tax_category.save
        format.html { redirect_to tax_category_url(@tax_category), notice: "Tax category was successfully created." }
        format.json { render :show, status: :created, location: @tax_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tax_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tax_categories/1 or /tax_categories/1.json
  def update
    respond_to do |format|
      if @tax_category.update(tax_category_params)
        format.html { redirect_to tax_category_url(@tax_category), notice: "Tax category was successfully updated." }
        format.json { render :show, status: :ok, location: @tax_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tax_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tax_categories/1 or /tax_categories/1.json
  def destroy
    @tax_category.destroy

    respond_to do |format|
      format.html { redirect_to tax_categories_url, notice: "Tax category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tax_category
      @tax_category = TaxCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tax_category_params
      params.require(:tax_category).permit(:tax_rate)
    end
end

app/helpers/tax_categories_helper.rb
module TaxCategoriesHelper
end

app/views/tax_categories/_form.html.erb
<%= form_with(model: tax_category, html: { class: "row g-3" }) do |form| %>
  <%= render 'shared/errors', object: tax_category %>

  <div class="col-md-3">
    <%= form.label :tax_rate, class: "form-label" %>
    <%= form.text_field :tax_rate, class: "form-control" %>
  </div>

  <div class="col-12">
    <%= form.submit "Submit", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/tax_categories/_tax_category.html.erb
<tr>
  <td scope="col"><%= tax_category.tax_rate %></td>
  <td scope="col">
    <%= link_to "Edit this item", edit_tax_category_path(tax_category), class: 'btn btn-info' %>
    <%= link_to "Destroy discount", [tax_category], data: {
                                  turbo_method: :delete,
                                  turbo_confirm: "Are you sure?"
                                  }, :class => 'btn btn-danger' %>
  </td>
</tr>

app/views/tax_categories/edit.html.erb
<h1>Editing tax category</h1>

<%= render "form", tax_category: @tax_category %>

<br>

<div>
  <%= link_to "Show this tax category", @tax_category, class: 'btn btn-info' %>
  <%= link_to "Back to tax categories", tax_categories_path, class: 'btn btn-info' %>
</div>

app/views/tax_categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tax categories</h1>

<%= link_to "New Tax Category", new_tax_category_path, class: 'btn btn-info' %>

<table class="table caption-top">
  <thead>
    <tr>
      <th>Tax rate</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <div id="tax_categories">
      <% @tax_categories.each do |tax_category| %>
        <%= render tax_category %>
      <% end %>
    </div>
  </tbody>
</table>

app/views/tax_categories/new.html.erb
<h1>New tax category</h1>

<%= render "form", tax_category: @tax_category %>

<br>
<%= link_to "Back to tax categories", tax_categories_path, class: 'btn btn-info' %>

app/views/tax_categories/show.html.erb
<p style="color: green"><%= notice %></p>

<table class="table caption-top">
  <thead>
    <tr>
      <th>Tax rate</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <%= render @tax_category %>
  </tbody>
</table>
<%= link_to "Back to items", tax_categories_path, class: 'btn btn-secondary' %>